"""004_update_prizes_and_topics

Revision ID: f268d319c538
Revises: 1542e9d8b82f
Create Date: 2026-06-26 18:19:55.363510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f268d319c538'
down_revision: Union[str, None] = '1542e9d8b82f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topics')
    op.drop_column('hackathon_prizes', 'place')
    op.drop_column('hackathon_prizes', 'description')
    op.add_column('hackathons', sa.Column('min_team_size', sa.Integer(), nullable=False))
    op.add_column('hackathons', sa.Column('max_team_size', sa.Integer(), nullable=False))
    op.add_column('hackathons', sa.Column('max_participants', sa.Integer(), nullable=False))
    op.add_column('hackathons', sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('hackathons', 'technologies')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hackathons', sa.Column('technologies', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('hackathons', 'topics')
    op.drop_column('hackathons', 'max_participants')
    op.drop_column('hackathons', 'max_team_size')
    op.drop_column('hackathons', 'min_team_size')
    op.add_column('hackathon_prizes', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('hackathon_prizes', sa.Column('place', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_table('topics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hackathon_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['hackathon_id'], ['hackathons.id'], name=op.f('topics_hackathon_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('topics_pkey'))
    )
    # ### end Alembic commands ###
