"""005_add_extra_hack_columns

Revision ID: b7d9764cc544
Revises: f268d319c538
Create Date: 2026-06-26 19:17:47.785817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'b7d9764cc544'
down_revision: Union[str, None] = 'f268d319c538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



hack_place_enum = postgresql.ENUM(
    "ONLINE",
    "MOSCOW",
    "SPB",
    "KAZAN",
    "NOVGOROD",
    name="hack_place_enum",
)

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    hack_place_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('hackathons', sa.Column('place', sa.Enum('Москва', 'Санкт-Петербург', 'Казань', 'Нижний-Новгород', 'Онлайн', name='hack_place_enum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hackathons', 'place')
    # ### end Alembic commands ###
