"""007_update_team_model

Revision ID: 558e5caf1d6d
Revises: f9a4ac1c9102
Create Date: 2026-07-01 00:23:02.864989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '558e5caf1d6d'
down_revision: Union[str, None] = 'f9a4ac1c9102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'description')
    # ### end Alembic commands ###
