"""009_add_hackathon_specification

Revision ID: 1d1fff6cdee1
Revises: a1b2c3d4e5f6
Create Date: 2026-07-04 19:29:23.114391

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '1d1fff6cdee1'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hackathon_specifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hackathon_id", sa.Integer(), nullable=False),
        sa.Column("task", sa.Text(), nullable=False),
        sa.Column("task_description", sa.Text(), nullable=True),
        sa.Column("functional_requirements", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("technical_limitations", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("evaluation_criteria", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("files", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(["hackathon_id"], ["hackathons.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hackathon_id"),
    )
    op.create_index(
        op.f("ix_hackathon_specifications_hackathon_id"),
        "hackathon_specifications",
        ["hackathon_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_hackathon_specifications_hackathon_id"), table_name="hackathon_specifications")
    op.drop_table("hackathon_specifications")
    # ### end Alembic commands ###
