"""010_delete_criteria_column

Revision ID: c7a7d3e9d493
Revises: 1d1fff6cdee1
Create Date: 2026-07-04 19:33:50.111681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7a7d3e9d493'
down_revision: Union[str, None] = '1d1fff6cdee1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hackathons', 'evaluation_criteria')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hackathons', sa.Column('evaluation_criteria', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
