"""011_fix_hack_specification

Revision ID: a1a55f671535
Revises: c7a7d3e9d493
Create Date: 2026-07-04 20:03:07.507188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1a55f671535'
down_revision: Union[str, None] = 'c7a7d3e9d493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Эта миграция не нужна, так как таблица уже создана в 009
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
