"""009_add hack_specification

Revision ID: a1a55f671535
Revises: c7a7d3e9d493
Create Date: 2026-07-04 20:03:07.507188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1a55f671535'
down_revision: Union[str, None] = 'c7a7d3e9d493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hackathon_specifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hackathon_id', sa.Integer(), nullable=False),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('task_description', sa.Text(), nullable=True),
    sa.Column('functional_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('technical_limitations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evaluation_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('files', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['hackathon_id'], ['hackathons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hackathon_specifications_hackathon_id'), 'hackathon_specifications', ['hackathon_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hackathon_specifications_hackathon_id'), table_name='hackathon_specifications')
    op.drop_table('hackathon_specifications')
    # ### end Alembic commands ###
