"""013_fix_submission_type

Revision ID: 576c06f698e7
Revises: ed6b32ec3d62
Create Date: 2026-07-05 00:30:40.178507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '576c06f698e7'
down_revision: Union[str, None] = 'ed6b32ec3d62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
