"""015_add_judge_score

Revision ID: dcf89eb69dc4
Revises: acd1db901f31
Create Date: 2026-07-05 02:29:16.278753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dcf89eb69dc4'
down_revision: Union[str, None] = 'acd1db901f31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('judge_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hackathon_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('judge_id', sa.Integer(), nullable=False),
    sa.Column('idea', sa.Integer(), nullable=False),
    sa.Column('implementation', sa.Integer(), nullable=False),
    sa.Column('quality', sa.Integer(), nullable=False),
    sa.Column('design', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hackathon_id'], ['hackathons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['judge_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'judge_id', name='unique_judge_score')
    )
    op.create_index(op.f('ix_judge_scores_hackathon_id'), 'judge_scores', ['hackathon_id'], unique=False)
    op.create_index(op.f('ix_judge_scores_judge_id'), 'judge_scores', ['judge_id'], unique=False)
    op.create_index(op.f('ix_judge_scores_team_id'), 'judge_scores', ['team_id'], unique=False)
    op.add_column('hackathon_specifications', sa.Column('submission_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('hackathons', 'submission_requirements')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hackathons', sa.Column('submission_requirements', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('hackathon_specifications', 'submission_requirements')
    op.drop_index(op.f('ix_judge_scores_team_id'), table_name='judge_scores')
    op.drop_index(op.f('ix_judge_scores_judge_id'), table_name='judge_scores')
    op.drop_index(op.f('ix_judge_scores_hackathon_id'), table_name='judge_scores')
    op.drop_table('judge_scores')
    # ### end Alembic commands ###
